import dotenv from "dotenv";
import { fileURLToPath } from "url";
import path from "path";
import pg from "pg";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(currentDir, "../../.env") });

const { Pool } = pg;
const connectionString = process.env.DATABASE_URL;
const connectionTimeoutMillis = Number(process.env.DB_CONNECTION_TIMEOUT_MS || 10000);
const pool = connectionString
  ? new Pool({ connectionString, connectionTimeoutMillis })
  : null;

export function databaseEnabled() {
  return pool !== null;
}

export function databaseConnectionSummary() {
  if (!connectionString) {
    return "DATABASE_URL is not configured";
  }

  try {
    const url = new URL(connectionString);
    const port = url.port || "5432";
    const database = url.pathname.replace(/^\//, "") || "<missing>";
    const sslMode = url.searchParams.get("sslmode") || "not-set";
    return `${url.protocol}//${url.username || "<missing-user>"}:***@${url.hostname}:${port}/${database}?sslmode=${sslMode}`;
  } catch {
    return "DATABASE_URL is set but is not a valid PostgreSQL URL";
  }
}

export function databaseFailureMessage(error) {
  const code = error?.code || error?.cause?.code || "UNKNOWN";
  const detail = error?.message || String(error);
  const networkCodes = new Set(["ECONNREFUSED", "ETIMEDOUT", "ENOTFOUND", "EAI_AGAIN"]);

  if (networkCodes.has(code) || /timeout|connect|network|socket/i.test(detail)) {
    return [
      "PostgreSQL target was configured, but the network connection failed.",
      "Likely causes: Zscaler, VPN, proxy, firewall, corporate policy, DNS, or outbound port 5432 being blocked.",
      "This is not a databaseEnabled=false problem. Ask IT to allow the Neon hostname on TCP port 5432, or test from an approved network.",
      `Driver error: ${code} - ${detail}`
    ].join("\n");
  }

  if (code === "28P01") {
    return `Neon rejected the username or password. Copy a fresh connection string from Neon.\nDriver error: ${code} - ${detail}`;
  }

  if (code === "3D000") {
    return `The database name in DATABASE_URL does not exist.\nDriver error: ${code} - ${detail}`;
  }

  if (code === "42501") {
    return `The Neon role does not have permission to create or use the orders table.\nDriver error: ${code} - ${detail}`;
  }

  return `PostgreSQL initialization failed.\nDriver error: ${code} - ${detail}`;
}

export async function initializeDatabase(seedOrder) {
  if (!pool) {
    return;
  }

  await pool.query(`
    CREATE TABLE IF NOT EXISTS orders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 6001) PRIMARY KEY,
      order_number VARCHAR(40) NOT NULL UNIQUE,
      status VARCHAR(30) NOT NULL,
      payment VARCHAR(30) NOT NULL,
      payment_method VARCHAR(40) NOT NULL,
      channel VARCHAR(20) NOT NULL,
      items JSONB NOT NULL,
      subtotal NUMERIC(12, 2) NOT NULL,
      shipping NUMERIC(12, 2) NOT NULL,
      discount NUMERIC(12, 2) NOT NULL,
      total NUMERIC(12, 2) NOT NULL,
      address VARCHAR(180) NOT NULL,
      delivery_slot VARCHAR(80),
      user_id VARCHAR(80) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query(
    `INSERT INTO orders (
       id, order_number, status, payment, payment_method, channel, items,
       subtotal, shipping, discount, total, address, delivery_slot, user_id
     ) VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9, $10, $11, $12, $13, $14)
     ON CONFLICT (id) DO NOTHING`,
    [
      seedOrder.id,
      seedOrder.orderNumber,
      seedOrder.status,
      seedOrder.payment,
      seedOrder.paymentMethod,
      seedOrder.channel,
      JSON.stringify(seedOrder.items),
      seedOrder.subtotal,
      seedOrder.shipping,
      seedOrder.discount,
      seedOrder.total,
      seedOrder.address,
      seedOrder.deliverySlot,
      "svc-retail-ops"
    ]
  );
}

export async function insertOrder(order, userId) {
  const result = await pool.query(
    `INSERT INTO orders (
       order_number, status, payment, payment_method, channel, items,
       subtotal, shipping, discount, total, address, delivery_slot, user_id
     ) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7, $8, $9, $10, $11, $12, $13)
     RETURNING *`,
    [
      order.orderNumber,
      order.status,
      order.payment,
      order.paymentMethod,
      order.channel,
      JSON.stringify(order.items),
      order.subtotal,
      order.shipping,
      order.discount,
      order.total,
      order.address,
      order.deliverySlot,
      userId
    ]
  );

  return mapOrderRow(result.rows[0]);
}

export async function findOrder(orderId) {
  const result = await pool.query("SELECT * FROM orders WHERE id = $1", [orderId]);
  return result.rows[0] ? mapOrderRow(result.rows[0]) : null;
}

export async function deleteOrder(orderId) {
  const result = await pool.query("DELETE FROM orders WHERE id = $1", [orderId]);
  return result.rowCount;
}

function mapOrderRow(row) {
  return {
    id: Number(row.id),
    orderId: Number(row.id),
    orderNumber: row.order_number,
    status: row.status,
    payment: row.payment,
    paymentMethod: row.payment_method,
    channel: row.channel,
    items: row.items,
    subtotal: Number(row.subtotal),
    shipping: Number(row.shipping),
    discount: Number(row.discount),
    total: Number(row.total),
    address: row.address,
    deliverySlot: row.delivery_slot,
    userId: row.user_id,
    createdAt: row.created_at.toISOString()
  };
}
