import pg from "pg";

const { Pool } = pg;
const connectionString = process.env.DATABASE_URL;
const pool = connectionString ? new Pool({ connectionString }) : null;

export function databaseEnabled() {
  return pool !== null;
}

export async function initializeDatabase(seedOrder) {
  if (!pool) {
    return;
  }

  await pool.query(`
    CREATE TABLE IF NOT EXISTS orders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 6001) PRIMARY KEY,
      order_number VARCHAR(40) NOT NULL UNIQUE,
      status VARCHAR(30) NOT NULL,
      payment VARCHAR(30) NOT NULL,
      payment_method VARCHAR(40) NOT NULL,
      channel VARCHAR(20) NOT NULL,
      items JSONB NOT NULL,
      subtotal NUMERIC(12, 2) NOT NULL,
      shipping NUMERIC(12, 2) NOT NULL,
      discount NUMERIC(12, 2) NOT NULL,
      total NUMERIC(12, 2) NOT NULL,
      address VARCHAR(180) NOT NULL,
      delivery_slot VARCHAR(80),
      user_id VARCHAR(80) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query(
    `INSERT INTO orders (
       id, order_number, status, payment, payment_method, channel, items,
       subtotal, shipping, discount, total, address, delivery_slot, user_id
     ) VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9, $10, $11, $12, $13, $14)
     ON CONFLICT (id) DO NOTHING`,
    [
      seedOrder.id,
      seedOrder.orderNumber,
      seedOrder.status,
      seedOrder.payment,
      seedOrder.paymentMethod,
      seedOrder.channel,
      JSON.stringify(seedOrder.items),
      seedOrder.subtotal,
      seedOrder.shipping,
      seedOrder.discount,
      seedOrder.total,
      seedOrder.address,
      seedOrder.deliverySlot,
      "svc-retail-ops"
    ]
  );
}

export async function insertOrder(order, userId) {
  const result = await pool.query(
    `INSERT INTO orders (
       order_number, status, payment, payment_method, channel, items,
       subtotal, shipping, discount, total, address, delivery_slot, user_id
     ) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7, $8, $9, $10, $11, $12, $13)
     RETURNING *`,
    [
      order.orderNumber,
      order.status,
      order.payment,
      order.paymentMethod,
      order.channel,
      JSON.stringify(order.items),
      order.subtotal,
      order.shipping,
      order.discount,
      order.total,
      order.address,
      order.deliverySlot,
      userId
    ]
  );

  return mapOrderRow(result.rows[0]);
}

export async function findOrder(orderId) {
  const result = await pool.query("SELECT * FROM orders WHERE id = $1", [orderId]);
  return result.rows[0] ? mapOrderRow(result.rows[0]) : null;
}

export async function deleteOrder(orderId) {
  const result = await pool.query("DELETE FROM orders WHERE id = $1", [orderId]);
  return result.rowCount;
}

function mapOrderRow(row) {
  return {
    id: Number(row.id),
    orderId: Number(row.id),
    orderNumber: row.order_number,
    status: row.status,
    payment: row.payment,
    paymentMethod: row.payment_method,
    channel: row.channel,
    items: row.items,
    subtotal: Number(row.subtotal),
    shipping: Number(row.shipping),
    discount: Number(row.discount),
    total: Number(row.total),
    address: row.address,
    deliverySlot: row.delivery_slot,
    userId: row.user_id,
    createdAt: row.created_at.toISOString()
  };
}
